"""create transfers

Revision ID: 4647b683a0ba
Revises: a0ef55fcc240
Create Date: 2021-01-13 12:08:33.939943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4647b683a0ba'
down_revision = 'a0ef55fcc240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('receiving_account', sa.String(length=255), nullable=False),
    sa.Column('sending_account', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transfers')
    # ### end Alembic commands ###
