"""create table

Revision ID: 743fb038fe7f
Revises: 74cf8b5c2e3e
Create Date: 2021-01-18 02:59:50.059154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743fb038fe7f'
down_revision = '74cf8b5c2e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account_transfers', ['user_id'])
    op.alter_column('checkings_account', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('virtual_cards', sa.Column('card_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_cards', 'card_number')
    op.alter_column('checkings_account', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'account_transfers', type_='unique')
    # ### end Alembic commands ###
